### PR TITLE
Don't fail in check mode

### PR DESCRIPTION
**Pull request by snopoke**
A few small changes to allow the role to run all the way through in check mode.

### CODE REVIEW

**Comment by snopoke** [comment]
Fixed build. Would be great to get this in so we don't keep seeing this error.

**Comment by mzrzvi** [comment]
@snopoke Strangely, this new change breaks my provisioning with the following error:

```
TASK [DavidWittman.redis : extract redis tarball] ******************************
fatal: [default]: FAILED! => {"failed": true, "msg": "The conditional check 'not ansible_check_mode' failed. The error was: error while evaluating conditional (not ansible_check_mode): 'ansible_check_mode' is undefined\n\nThe error appears to have been in '/Users/moizrizvi/Lawyaw/code/mystacksdev/provisioning/roles/DavidWittman.redis/tasks/download.yml': line 26, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: extract redis tarball\n  ^ here\n"}
```

If I revert both changes made in this PR, it works fine. Any thoughts?

**Comment by snopoke** [comment]
@mzrzvi what version of Ansible are you running? The `ansible_check_mode` var was only added in v2.1: https://docs.ansible.com/ansible/latest/user_guide/playbooks_checkmode.html#information-about-check-mode-in-variables

**Comment by mzrzvi** [comment]
@snopoke I'm using 2.6.0 so I'm not sure why it wouldn't work

**Pull request merged**
