### PR TITLE
Replace deprecated "include" with "include_tasks"

### PR DESCRIPTION
**Pull request by mattock**
The existing code does not work on any semi-recent Ansible versions.

### CODE REVIEW

**Comment by mattock** [comment]
This issue has been reported in https://github.com/DavidWittman/ansible-redis/issues/281 and was fixed earlier in two unmerged and outdated PRs:

* https://github.com/DavidWittman/ansible-redis/pull/178
* https://github.com/DavidWittman/ansible-redis/pull/189

It would be nice if this trivial fix could be merged.

**Comment by jof** [comment]
+1 for merging this; this role is currently totally broken on modern ansible these days.

**Comment by DavidWittman** [comment]
Thanks for the nudge. Merged.

**Comment by thbar** [comment]
Thank you!

**Pull request merged**
