### PR TITLE
Save people literally hours of debugging

### PR DESCRIPTION
**Pull request by rromanchuk**

### CODE REVIEW

**Comment by DavidWittman** [comment]
What does this fix?

**Comment by thbar** [comment]
I wonder the same: is it because the published version on Galaxy is old (https://galaxy.ansible.com/davidwittman/redis), or because of another problem?

**Comment by rromanchuk** [comment]
I'm not sure anymore, i need sleep. I made a mistake when modernizing and moving [aws ssm](https://aws.amazon.com/systems-manager/) to execute my plays, where my legacy local `requirements.yml` was using git, and new deployment was galaxy when i realized the galaxy-installed-on-the-fly role was using different source. Probably user error and being dramatic while fighting fires. aka, took master down because i deployed a bogus/miconfigured service file 🤣

**Comment by DavidWittman** [comment]
All good... We've all been there!

**Comment by rromanchuk** [comment]
[finally tailing logs now] looks like i also forked without forking. I'm sure i made some sort of bargain with myself that it was only "temporary, just for a quick test", i have a monkey patched `redis.service.j2` that looks like i would update from upstream with -f then hand patch for at least a couple of versions now, ....so much for temporary. 

In my context, the server has no inbound/outbound www access from/to the vpc. To make provisioning a delight, there is an efs mount on ~/, ready to go at boot, with this role, hosts of any arch can load/save the .rdb by just changing the tag value on ec2.  The `ProtectHome=yes` line causes systemd to implode on `ExecStart`, and in my case, if someones reading my process list, it's already game over.  So it wasn't even from the version change, which at most lost some .conf values like `redis_config_additional`,  just the classic case of lazy developer kindling their own fire for future self to enjoy a year later lol

**Pull request closed without merging**
