### PR TITLE
Upgrade option for reinstallation

### PR DESCRIPTION
**Pull request by rayalan**
Pull request for #51. 

Also adds cleanup after installation to remove /usr/local/src/redis files (both tarball and build files)

### CODE REVIEW

**Comment by DavidWittman** [comment]
Thanks again @rayalan, I really appreciate you working toward closing #51.

It looks like this branch is failing the Travis tests because some of the tasks in your changes are not idempotent. In other words, the role should have 0 changed tasks on a second consecutive run.

I'll take some time to test and review this soon.

**Comment by rayalan** [comment]
@DavidWittman Ah, I see. Is there an easy way to get the log from the second run? It looks like it is only being fed into the grep.

**Comment by DavidWittman** [comment]
@rayalan Doesn't look like it... that's a bummer. If you run the test back to back on an Ubuntu box there should be no changes on the second run. I'll dig up some more info if you're unable to reproduce the issue.

**Comment by DavidWittman** [comment]
Here's a log from a second Ansible run from your branch:

```
$ ansible-playbook -i redacted, -u root redis-single.yml

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [redacted]

TASK: [redis | check for prior redis installation] ****************************
changed: [redacted]

TASK: [redis | install dependencies] ******************************************
ok: [redacted] => (item=gcc,make,libc6-dev)

TASK: [redis | install dependencies] ******************************************
skipping: [redacted]

TASK: [redis | enable overcommit in sysctl] ***********************************
ok: [redacted]

TASK: [redis | add redis user] ************************************************
ok: [redacted]

TASK: [redis | download redis] ************************************************
changed: [redacted]

TASK: [redis | upload redis] **************************************************
skipping: [redacted]

TASK: [redis | extract redis tarball] *****************************************
changed: [redacted]

TASK: [redis | compile redis] *************************************************
changed: [redacted]

TASK: [redis | create redis install directory] ********************************
ok: [redacted]

TASK: [redis | create /etc/redis] *********************************************
ok: [redacted]

TASK: [redis | create /var/run/redis] *****************************************
ok: [redacted]

TASK: [redis | install redis] *************************************************
ok: [redacted]

TASK: [redis | remove redis build files] **************************************
changed: [redacted]

TASK: [redis | create redis working directory] ********************************
ok: [redacted]

TASK: [redis | create redis init script] **************************************
ok: [redacted] => (item=/Users/dw/Projects/ansible/roles/redis/templates/Debian/redis.init.j2)

TASK: [redis | set redis to start at boot] ************************************
ok: [redacted]

TASK: [redis | check if log file exists] **************************************
ok: [redacted]

TASK: [redis | ensure that log file exists and is writable by redis] **********
skipping: [redacted]

TASK: [redis | create redis config file] **************************************
ok: [redacted]

TASK: [redis | add redis init config file] ************************************
skipping: [redacted]

TASK: [redis | add redis init config file] ************************************
ok: [redacted]

NOTIFIED: [redis | remove redis tarball] **************************************
changed: [redacted]

TASK: [redis | ensure redis is running] ***************************************
ok: [redacted]

TASK: [redis | create sentinel working directory] *****************************
skipping: [redacted]

TASK: [redis | create sentinel init script] ***********************************
skipping: [redacted] => (item=/Users/dw/Projects/ansible/roles/redis/templates/Debian/redis_sentinel.init.j2)

TASK: [redis | set sentinel to start at boot] *********************************
skipping: [redacted]

TASK: [redis | check if sentinel log file exists] *****************************
skipping: [redacted]

TASK: [redis | ensure that sentinel log file exists and is writable by redis] ***
skipping: [redacted]

TASK: [redis | create sentinel config file] ***********************************
skipping: [redacted]

TASK: [redis | add sentinel init config file] *********************************
skipping: [redacted]

TASK: [redis | add sentinel init config file] *********************************
skipping: [redacted]

TASK: [redis | ensure sentinel is running] ************************************
skipping: [redacted]

TASK: [redis | create facts directory] ****************************************
ok: [redacted]

TASK: [redis | create redis facts] ********************************************
ok: [redacted]

PLAY RECAP ********************************************************************
redacted              : ok=24   changed=6    unreachable=0    failed=0
```

Anything which is `changed` should be `ok`.

**Comment by rayalan** [comment]
@DavidWittman I found the problem with the original proposal. (I'd missed that redis-server isn't in $PATH on the subsequent runs, so checking for version needs to explicitly call the redis-server binary by full path.)

I also added three more fixes, one of which requires a test change (or I can split these into separate pull requests if you prefer):
* Test breaking change: Facts are really per server (e.g. if you run the role twice on the same computer with different ports, the facts are not idempotent). So I added port to the facts file which is why the facts test is now failing.
* I think the 'creates' portion on the install is wrong since it means the installation won't happen if redis-server already exists as a binary.
* The service enable/disable didn't work for me on CentOS 7 due to a lack of a status command in init.d/conf. I added that and everything seems to work much better now.

**Comment by DavidWittman** [comment]
Hey Alan... Sorry I've fallen a little behind on this. I'm going to take some time to review your proposal. At first glance, we're going to need the `creates`

**Comment by Migsi** [comment]
Any news on this PR? Might be helpful when upgrading versions, which should have happened quite a bit for people using this role since the last 5 years.

**Pull request closed without merging**
